name: Build & Deploy to Cloudflare Worker

on:
  push:
    branches:
      - main
  repository_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "15.6.0"
      - run: npm install -D vuepress
      - run: npm i vuepress-theme-default-prefers-color-scheme
      - run: npm install -D @vuepress/plugin-back-to-top
      - run: npm install -D vuepress-plugin-container
      - run: npm run docs:build
      # - run: npm run docs:dev
        env:
          CI: true
      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{secrets.CF_API_TOKEN}}
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
          CF_ZONE_ID: ${{secrets.CF_ZONE_ID}}
          USER: root
